version: "3.9"

services:
  php:
    build: .
    #image: pierro:1.O
    container_name: "php"
    restart: always
    volumes:
      - .:/var/www/html
    env_file:
      - .env
      - .env.local
    depends_on:
      - db
    networks:
      - dev

  nginx:
    image: nginx:1.14.2-alpine
    container_name: "nginx"
    restart: always
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./config/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    depends_on:
      - php
    env_file:
      - .env
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - dev

  db:
    image: mysql
    container_name: db_docker_mysql_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: "ecoit"
    ports:
      - "3350:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
